### ISSUE TITLE
Customize group org-highlight-hydra

### ISSUE THREAD

**Issue by Ypot** [panapnamana/org-highlight-hydra#1]
Working!!!
But, what about a customize menu to set the emphasis and hydra?

**Comment by panapnamana** [comment]
Wow you actually checked it out! How cool! And it is working!

Regarding the menu:
I don't think I would want to code something like that, except when many people want that, as it is very easy to make the changes in the code itself to make it suit your needs.
To change the emphasis symbol simply google the utf-8 symbol you want to use and copy-paste it into the place where you find the symbols inside extra-emphasis.el
To change the faces there already is the build in menu from emacs.
To alter the hydra just add/remove stuff from the existing one, using it as a  template.

Why would you need such a menu? To adept the hydra on the fly for several projects?

**Comment by Ypot** [comment]
Hi!!
I checked and tweaked it!!! hahaha

I asked for the customize menu, because it seemed that changes would have to be done in too many places. 

I changed some symbols here:
`(setq my-emph-symbol-plist '(título "🗖" subrayado2 "≟" magenta "↯" comment "፧" bold "*" italic "/" verbatim "=" strikethrough "+" underline "_" code "~"))`

But changes must be done here too?:

```

(defhydra hydra-org-highlight-menu (:color blue)
  "
Emphasize^     ^Highlight
------------------------------
_b_: bold      _t_: título
_i_: italic    _S_: subrayado2
_u_: underline _m_: magenta
_v_: verbatim  _c_: cyan
_s_: strike    ^^
_C_: code      ^^
"
  ("b" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'bold)))
  ("i" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'italic)))
  ("u" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'underline)))
  ("v" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'verbatim)))
  ("s" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'strikethrough)))
  ("C" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'code)))
  ("m" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'important)))  
  ("q" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'question)))
  ("p" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'problem)))
  ("c" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'comment))))
```

And I had to coordinate all of that with the org-emphasize settings. And my brain fused xD

Maybe some dummy instructions in the README would do?

**Comment by panapnamana** [comment]
You did not tell the hydra the function for retireving the symbol in the list my-emph-symbol-list.
The function in the hydra "surround-region-with-arg-symbol" takes a symbol and places it around the active region.
The list my-emph-symbol-list holds the symbols and the keys to retrieve the symbols with plist-get from the list.
From what I can see you changed the layout of what your hydra pop up displays (that is the upper part) but you did not change the actual function calls to be executed when you press the keys (that happens in the lower part). You must add the function calls for the respective key presses t, S, m, c.
1. Add the key-symbol pair to the list (like you have done already).
2. Add a line to the lower part of the hydra with for example ("S" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'subrayado2)))
3. remove the lines from the lower part of the hydra you don't need, like ("m" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'important)))  

I hope this helps!

**Comment by Ypot** [comment]
Of course it helps (and it works too)!:

```

(setq my-emph-symbol-plist '(title "℄" subrayado2 "﹏" overline "˙" cyan "∠" magenta "🤍" yellow "▽" green "✡" red "⎊"))


(defhydra hydra-org-highlight-menu (:color blue)
  "
Emphasize^     ^Highlight
------------------------------
_t_: title      _y_: yellow
_o_: overline   _g_: green
_c_: cyan       _r_: red
_m_: magenta    ^^
"

  ("t" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'title)))  
  ("o" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'overline)))
  ("c" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'cyan)))
  ("m" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'magenta)))
  ("y" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'yellow)))
  ("g" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'green)))
  ("r" (surround-region-with-arg-symbol (plist-get my-emph-symbol-plist 'red))))

```
